import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import NoSSRProvider from "@/components/provider/NoSSRProvider";
export const metadata: Metadata = {
  title: "Mayur's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SpeedInsights />
      <html lang="en">
        <body className={` antialiased`}>
          <NoSSRProvider>
            <Header />
            {children}
            <Footer />
          </NoSSRProvider>
        </body>
      </html>
    </>
  );
}
